[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  
[[redirects]]
  from = "/slack/events"
  to = "/.netlify/functions/slack-events"
  status = 200

[[redirects]]
  from = "/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "/.netlify/functions/auth-callback"
  status = 200

[[redirects]]
  from = "/slack/oauth/callback"
  to = "/.netlify/functions/slack-oauth-callback"
  status = 200


